version: "3.8"

services:
  db_speaker_generator:
    image: postgres:14.8
    container_name: db_speaker_generator
    # restart: always
    ports:
      - 9492:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_speaker_generator
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: